USE master
GO
IF DB_ID('BlogDB') IS NOT NULL
BEGIN
  ALTER DATABASE BlogDB
  SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE BlogDB
END
GO

CREATE TABLE Tags(
	ID int IDENTITY NOT NULL,
	Name nvarchar(50) NOT NULL,
  CONSTRAINT PK_Tags PRIMARY KEY (ID))

ALTER TABLE Comments ADD CONSTRAINT DF_Comments_Date DEFAULT GETDATE() FOR Date

DROP TABLE Tags